version: '3'

# Production Docker Compose Configuration
# Optimized for production deployment with security and performance best practices

services:
  pgvector:
    image: agnohq/pgvector:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backups:/backups
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: md5
      # Production tuning
      POSTGRES_MAX_CONNECTIONS: ${POSTGRES_MAX_CONNECTIONS:-100}
      POSTGRES_SHARED_BUFFERS: ${POSTGRES_SHARED_BUFFERS:-256MB}
    networks:
      - agent-os
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  agno-backend-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ${IMAGE_NAME:-agent-os}:${IMAGE_TAG:-latest}
    command: app
    restart: always
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      # Database
      DB_HOST: pgvector
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_DATABASE: ${DB_NAME}
      
      # API Keys
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      
      # App Configuration
      PORT: 8000
      WAIT_FOR_DB: "True"
      INIT_DB: "True"
      PRINT_ENV_ON_LOAD: "False"
      
      # Feature Flags
      ENABLE_MEMORY: ${ENABLE_MEMORY:-True}
      ENABLE_VECTOR_RAG: ${ENABLE_VECTOR_RAG:-True}
      ENABLE_VALIDATION: ${ENABLE_VALIDATION:-True}
      
      # Performance (Production)
      WORKERS: ${WORKERS:-4}
      UVICORN_RELOAD: "False"
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
      # Security
      CORS_ORIGINS: ${CORS_ORIGINS:-https://yourdomain.com}
    networks:
      - agent-os
    depends_on:
      pgvector:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    networks:
      - agent-os
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - agent-os
    depends_on:
      - agno-backend-api
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  agent-os:
    driver: bridge

volumes:
  pgdata:
    driver: local
  redis-data:
    driver: local
